name: mymedicinemobile
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_svg: ^1.1.6

  shared:
      path: ../_shared

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/PoppinsBold-GdJA.otf
          weight: 700
        - asset: assets/fonts/PoppinsMedium-1JPv.otf
          weight: 500
        - asset: assets/fonts/PoppinsRegular-B2Bw.otf
          weight: 400
        - asset: assets/fonts/PoppinsSemibold-8l8n.otf
          weight: 500
        - asset: assets/fonts/PoppinsThin-rO2B.otf
          weight: 300
