name: flutter_flutterwave
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  flutter_dotenv: ^5.0.2
  flutterwave_standard: 1.0.2

  shared:
      path: ../_shared

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
